# Generated by Django 6.1.1 on 2026-09-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(max_length=1),
        ),
    ]
