# Generated by Django 6.1.1 on 2026-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.IntegerField(),
        ),
    ]
